### ISSUE TITLE
**Footer**

### ISSUE THREAD

**Issue by rockycodes** [ProgressiveHackNight/no-amazon-hq2#9]
Make component:
- contact us
- social media icons/links

**Comment by BatMiles** [comment]
I can take this one

**Comment by rockycodes** [comment]
Awesome! I'll add you to the repo so you can work on it. Tbd about email and social media links (I'll ask the coalition) but in the meantime if you can get it set up so all we have to do is plop in the links that's great! Are you with TWC or Prog Hacknight?

**Comment by BatMiles** [comment]
TWC!

**Comment by rockycodes** [comment]
Hey BatMiles! Just checking if you're working on this ticket?

**Comment by BatMiles** [comment]
Yeah! I can’t til tomorrow though, so if there’s a rush someone else can take it and I’ll take something else

**Comment by rockycodes** [comment]
Sweet! No rush just wondering what I should pick up today. Is it ok if I assign the ticket to you and move it to in progress?

**Comment by rockycodes** [comment]
nm just saw you did.
